// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOoPwPB5TWO7mBYfYfimi1TYepOPuv2s4',
    appId: '1:130136736168:web:65d7264e65072ee8f31d9d',
    messagingSenderId: '130136736168',
    projectId: 'ecommerce2-414b5',
    authDomain: 'ecommerce2-414b5.firebaseapp.com',
    storageBucket: 'ecommerce2-414b5.appspot.com',
    measurementId: 'G-K2FE69SBE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFtVYReOC4fYJWfILms93uJEAmE0kqZ84',
    appId: '1:130136736168:android:266a36b98a768dbbf31d9d',
    messagingSenderId: '130136736168',
    projectId: 'ecommerce2-414b5',
    storageBucket: 'ecommerce2-414b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlG2jGbIjnNNUvqTcxLGOrFK-k11m1xts',
    appId: '1:130136736168:ios:20a67036a2bf98daf31d9d',
    messagingSenderId: '130136736168',
    projectId: 'ecommerce2-414b5',
    storageBucket: 'ecommerce2-414b5.appspot.com',
    iosBundleId: 'com.example.ecommece2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlG2jGbIjnNNUvqTcxLGOrFK-k11m1xts',
    appId: '1:130136736168:ios:e0cedfb33b13154ef31d9d',
    messagingSenderId: '130136736168',
    projectId: 'ecommerce2-414b5',
    storageBucket: 'ecommerce2-414b5.appspot.com',
    iosBundleId: 'com.example.ecommece2.RunnerTests',
  );
}
